theme: jekyll-theme-cayman
title: Open Refine Tutorial
description: Cleaning Messy Data. This site is currently being remediated for accessibility. If you need an accessible copy of any content on this site, please contact us at [dsds@ou.edu](mailto:dsds@ou.edu) 
level: Beginner
